### PR TITLE
#360 update data so all items have strength or unit of use

### LINKED ISSUE #360: Update master spreadsheet so all items have strength or unit of use
Required for https://github.com/sussol/msupply/issues/8272

## Expected Behaviour

All existing items on https://universalcodes.msupply.org.nz/ should be searchable in v2.0.0 of UC 

## Current Behaviour

Some items are missing strength or unit of use codes which means the item won't show up in mSupply

## Possible Solution

Update all items such that there is either a strength or unit of use present (for a lot of consumables, this will be '1')

This will be done by transferring UC2 to UC7 for these items, and then generating new UC2 codes for them.

## Steps to Reproduce (bugs only, delete if not applicable)

1. Search in mSupply for any of the items in this spreadsheet (in the universal codes search box):
[Items without strength or unit 19 March.xlsx](https://github.com/openmsupply/unified-codes/files/6193180/Items.without.strength.or.unit.19.March.xlsx)
2. Observe no results returned

### PR DESCRIPTION
**Pull request by katherine-sussol**
Fixes #360 

## Description

- Updated products.csv with new data format (so all items have strength and/or unit of use)
- Updated data parser to correctly load these new nodes
- Updates to mSupply query so items show up in mSupply as expected
- Some minor offroads (will be noted in comments)

### Documentation:

Tick below if one of the following applies:

1. Documentation has been added to cover changes introduced by this PR.
2. This PR requires no changes to documentation.

- [x] Documentation OK.

### Tests:

Tick below if one of the following applies:

1. Tests have been added to cover changes introduced by this PR.
2. This PR requires no new tests.

- [x] Tests OK.

### CODE REVIEW

File: unified-codes/apps/data-service/src/app/v1/schema.ts [hunk 1]
```diff
@@ -19,6 +19,10 @@ export class EntityType implements IEntity {
   @Field((type) => [EntityType], { nullable: true })
   children: IEntity[];
 
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
+  @Field((type) => [EntityType], { nullable: true })
+  parents: IEntity[];
```
Comment (katherine-sussol) [inline unified-codes/apps/data-service/src/app/v1/schema.ts:24]: This was added with the intention to later remove `product` from the schema.

File: unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts [hunk 2]
```diff
@@ -156,9 +156,11 @@ export class DgraphDataSource extends RESTDataSource {
             description: name@*
           }
           children {
+            code
```
Comment (katherine-sussol) [inline unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts:159]: Some codes were missing, guessing maybe it wasn't possible before but with all these new level mappings it's now possible? 🤷  was causing some items in mSupply to not show up

File: unified-codes/apps/web/.storybook/tsconfig.json [hunk 3]
```diff
@@ -1,6 +1,7 @@
 {
   "extends": "../../../tsconfig.base.json",
   "compilerOptions": {
+    "jsx": "react",
```
Comment (katherine-sussol) [inline unified-codes/apps/web/.storybook/tsconfig.json:4]: Looking back I think I was getting some warnings and made this change, can remove if it was just me

File: unified-codes/apps/web/src/components/containers/detail/DetailEntityListItem.tsx [hunk 4]
```diff
@@ -104,6 +104,7 @@ const DetailEntityListItemComponent: DetailEntityListItem = ({
           parentDescription = `${entityDescription} ${description}`;
           break;
         case 'unit_of_use':
+        case 'strength':
```
Comment (katherine-sussol) [inline unified-codes/apps/web/src/components/containers/detail/DetailEntityListItem.tsx:107]: Previously the lowest level was only 'unit_of_use' but now we can go down to strength, was causing entity descriptions to appear truncated

File: unified-codes/apps/web/src/components/containers/detail/DetailProduct.tsx [hunk 5]
```diff
@@ -64,8 +64,8 @@ export const DetailProductComponent: DetailProduct = ({ entity, fetchEntity }) =
         Product
       </Typography>
       <Typography className={classes.product} onClick={onProductClick}>
-        <Typography>{description}</Typography>
-        <Typography className={classes.code}>{code}</Typography>
+        {description}
```
Comment (katherine-sussol) [inline unified-codes/apps/web/src/components/containers/detail/DetailProduct.tsx:67]: Got JSX validation error about nested `<p>` tags. I think this is going to be removed anyway soon

File: unified-codes/apps/web/src/sagas/DetailSaga.ts [hunk 6]
```diff
@@ -44,6 +44,18 @@ const getEntityQuery = (code: string) => `
       type
       description
     }
+    parents {
```
Comment (katherine-sussol) [inline unified-codes/apps/web/src/sagas/DetailSaga.ts:47]: Intended as a replacement for product fetching. Happy to remove if objections 🤣

**Comment by katherine-sussol** [comment]
Bit stale now so there are a lot of merge conflicts... taking a 👀

File: unified-codes/apps/web/src/sagas/DetailSaga.ts (hunk 6 above)
Comment (mark-prins) [reply unified-codes/apps/web/src/sagas/DetailSaga.ts:47]: can an entity have multiple parents? wondering why this is an array

Comment (wlthomson) [reply unified-codes/apps/web/src/sagas/DetailSaga.ts:47]: As of recent changes, the `product` field  has been made redundant... so might be able to get rid of this entirely anyway? Although, to keep the GraphQL as flexible as possible, just having this field which exposes the reverse edge for `children` is probably a good idea (I don't think there are any entities with multiple parents, but since it's an array in the Dgraph data model, may as well keep it that way for simplicity and future-proofing)?

File: unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts (hunk 2 above)
Comment (wlthomson) [reply unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts:159]: mSupply is now directly grabbing entities at the `Unit` and `DoseStrength` levels, so I think all this stuff is no longer needed!

File: unified-codes/apps/web/src/sagas/DetailSaga.ts (hunk 6 above)
Comment (wlthomson) [reply unified-codes/apps/web/src/sagas/DetailSaga.ts:47]: Also just a note that this isn't needed right now, as the web UI only traverses downwards. We definitely want to be able to see parents, and I think updating the `DetailPage` to pre-expand the list to show the entity and it's parents is the easy solution to this. This will require this field, so that's why I don't have an objection to keeping it in there even though we won't be using it right now.

File: unified-codes/apps/web/.storybook/tsconfig.json (hunk 3 above)
Comment (katherine-sussol) [reply unified-codes/apps/web/.storybook/tsconfig.json]: Already done in a different PR so this is gonezers after merge

File: unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts (hunk 2 above)
Comment (katherine-sussol) [reply unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts]: Yup this stuff is all gone after merging in `master` 🥳

File: unified-codes/apps/web/src/components/containers/detail/DetailEntityListItem.tsx (hunk 4 above)
Comment (katherine-sussol) [reply unified-codes/apps/web/src/components/containers/detail/DetailEntityListItem.tsx]: Component no longer does specific type mapping so this change has also gone after merging in `master`

File: unified-codes/apps/web/src/components/containers/detail/DetailProduct.tsx (hunk 5 above)
Comment (katherine-sussol) [reply unified-codes/apps/web/src/components/containers/detail/DetailProduct.tsx]: No more DetailProduct.tsx

**Comment by katherine-sussol** [comment]
Merge done - ready again for review 👍

File: unified-codes/apps/web/src/sagas/DetailSaga.ts (hunk 6 above)
Comment (katherine-sussol) [reply unified-codes/apps/web/src/sagas/DetailSaga.ts]: Hm yeah, I don't think there is currently a use case for multiple `parents` (although there will potentially be multiple levels of `parent`s above any given node). The schema does allow it though because it's a direct reversal of `children` which is an array 🤔 . I guess we could add parents manually as a separate edge but thought using reverse edge would be simpler 😆

**Review by wlthomson — APPROVED** [review]
LGTM!

Nit: for another issue, but I think also need to add some conditional logic to the web UI:

image
