### PR TITLE
#194 update dependencies

### LINKED ISSUE #194: Update dependencies
It's that time again! 

Spurred on by  `Module not found: Error: Can't resolve 'reselect'` which I'm getting in `master`
Also `found 38 vulnerabilities (32 low, 1 moderate, 5 high)`

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #194 

## Description
Updated dependencies and tested that these all compile and run:

- web
- data-service
- legacy-api
- storybook web
- storybook ui

There are still 8 security issues. I've manually patched up the two highs in `package.json` but really, these are waiting for `@nrwl/web` to update its dependencies.

### Documentation:

Tick below if one of the following applies:

1. Documentation has been added to cover changes introduced by this PR.
2. This PR requires no changes to documentation.

- [ ] Documentation OK.

### Tests:

Tick below if one of the following applies:

1. Tests have been added to cover changes introduced by this PR.
2. This PR requires no new tests.

- [ ] Tests OK.

### CODE REVIEW

File: unified-codes/apps/web/src/components/templates/Details.tsx [hunk 1]
```diff
@@ -11,10 +11,14 @@ export interface DetailsProps {
...
 
+interface IDetailsParameters {
+  code: string;
+}
+
 export type Details = React.FunctionComponent<DetailsProps>;
 
 export const DetailsComponent: Details = ({ entity, getEntity }) => {
-  const { code } = useParams();
+  const { code } = useParams<IDetailsParameters>();
```
Comment (katherine-sussol) [inline unified-codes/apps/web/src/components/templates/Details.tsx:21]: I guess this is a dependency of sorts 🤔 . Like the change though 👍

**Review by katherine-sussol — APPROVED** [review]
That's a lot of out of date dependencies! 🙀 
Looks good to me 🙇‍♀️

File: unified-codes/apps/web/src/components/templates/Details.tsx (hunk 1 above)
Comment (mark-prins) [reply unified-codes/apps/web/src/components/templates/Details.tsx:21]: soz! I should have confessed that offroad! typescript whined, so I tinkered.
