### PR TITLE
#320 error in eml properties

### LINKED ISSUE #320: mSupply unable to save EML properties
Issue raised in testing: https://github.com/sussol/msupply/issues/8100#issuecomment-787479540

Unable to save WHO EML properties

## Possible Solution
The code used in the data parser is `code_eml` but mSupply is looking for `who_eml`

## Steps to Reproduce (bugs only, delete if not applicable)

1. Lookup a universal code in mSupply
2. Check the reporting tab of the item and the log

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #320 

## Description
Change code from `code_eml` to `who_eml` and test.

### Documentation:

Tick below if one of the following applies:

1. Documentation has been added to cover changes introduced by this PR.
2. This PR requires no changes to documentation.

- [ ] Documentation OK.

### Tests:

Tick below if one of the following applies:

1. Tests have been added to cover changes introduced by this PR.
2. This PR requires no new tests.

- [ ] Tests OK.

### CODE REVIEW

File: unified-codes/release-uc.sh [hunk 1]
```diff
@@ -0,0 +1,58 @@
+### unified codes release steps                     ###
```
Comment (mark-prins) [inline unified-codes/release-uc.sh:1]: I've been leaving this out of the codebase, but it is very useful. Time to include it?

Comment (wlthomson) [reply unified-codes/release-uc.sh:1]: Nice!

**Review by wlthomson — APPROVED** [review]
LGTM!
