### PR TITLE
#25 Update mapper.js

### LINKED ISSUE #25: Items endpoint failing invalid params test
As per screenshot below:
Screen Shot 2020-07-03 at 10 29 57 AM

UPDATE post-fix: 
mapper.js had some minor issues which meant the request would not get blocked:
- request.params is null in function (changed to request.query)
- request.url is null in function (changed to request.raw.url)
- full url with query string wasn't matching key to access PARAMETERS object
- reduce function was returning strange results e.g:
  - items?invalid=data&test=moredata => { valid: [], invalid: { query: 'test' } } 
  - updated to do simple filter of params on whitelist

### PR DESCRIPTION
**Pull request by katherine-sussol**
Fixes #25 

Found a few minor issues:
- request.params is null in function (changed to request.query)
- request.url is null in function (changed to request.raw.url)
- full url with query string wasn't matching key to access PARAMETERS object
- reduce function was returning strange results e.g.:
  - items?invalid=data&test=moredata => { valid: [], invalid: { query: 'test' } } 
  - Changed to filter on whitelist - simpler but not as fancy (could see what it was trying to do - for educational purposes may test it locally some more)

Happy to hear if any of the changes could be done better!

### CODE REVIEW

File: api/src/mappers.js [hunk 1]
```diff
@@ -10,18 +10,16 @@ const PARAMETERS = {
...
-  const whitelist = PARAMETERS[url];
-  const { params } = request;
-  return Object.keys(params).reduce(
-    ({ parameters }, param) => {
-      const { valid: validParameters, invalid: invalidParameters } = parameters;
-      if (whitelist.includes(param))
-        return { parameters: { valid: { ...validParameters, param }, invalid: invalidParameters } };
-      return { parameters: { valid: validParameters, invalid: { ...invalidParameters, param } } };
+  const { url } = request.raw;
+  const whitelist = PARAMETERS[url.split('?')[0]];
```
Comment (wlthomson) [inline api/src/mappers.js:14]: Nit: is there a way to get the base url (i.e. without splitting on the query param)?

Comment (wlthomson) [inline api/src/mappers.js:14]:
```suggestion
  const [baseUrl] = url.split('?');
  const whitelist = PARAMETERS[baseUrl];
```

File: api/src/mappers.js [hunk 2]
```diff
@@ -10,18 +10,16 @@ const PARAMETERS = {
...
+  const { query } = request;
+
+  return {
```
Comment (wlthomson) [inline api/src/mappers.js:17]: Nice!

File: api/src/mappers.js (hunk 1 above)
Comment (katherine-sussol) [reply api/src/mappers.js:14]: Oh cool that's a lot easier to read :)

Comment (katherine-sussol) [reply api/src/mappers.js]: That's a good question! I had a look and both the Fastify request object and the raw request object don't seem to have it conveniently available without the query param. The hostname portion is, but that's not so useful for us in this instance 😿
