### PR TITLE
#385 new codes for covid vaccines

### LINKED ISSUE #385: New Codes for COVID-19 Vaccines
Initiated from https://support.msupply.org.nz/cerb6/profiles/ticket/TH-5195-TJ

## Expected Behaviour

UC Web and API to include codes for the various COVID-19 vaccines available

## Current Behaviour

No COVID-19 Vaccines (actually there are currently no vaccines in UC)

## Possible Solution

Confirm format/data/codes and upload

## Steps to Reproduce (bugs only, delete if not applicable)

1. Search for 'Vaccine' in the Web UI or in mSupply in the Universal Codes interface

### PR DESCRIPTION
**Pull request by katherine-sussol**
Fixes #385

## Description

- New codes, the csv diff is being super weird again, manually removed trailing lines at the end 
- This was again done in a bit of a rush as there was some waiting on them over the Easter break 🙀 
  - https://support.msupply.org.nz/cerb6/profiles/ticket/TH-5195-TJ
- I initially removed the code generation to property nodes (just getting impatient and wanting it to go faster haha). Have since removed with 19d6968c1 and 0735e5930 as should probably be done against #357

### Documentation:

Tick below if one of the following applies:

1. Documentation has been added to cover changes introduced by this PR.
2. This PR requires no changes to documentation.

- [x] Documentation OK.

### Tests:

Tick below if one of the following applies:

1. Tests have been added to cover changes introduced by this PR.
2. This PR requires no new tests.

- [x] Tests OK.

### CODE REVIEW

File: unified-codes/apps/data-loader/src/app/v2/DataParser.ts [hunk 1]
```diff
@@ -609,7 +609,7 @@ export class DataParser {
         // });
 
         // Process external properties at product (UC2) level
-        if (!uc7 && uc2) {
+        if (uc2) {
```
Comment (katherine-sussol) [inline unified-codes/apps/data-loader/src/app/v2/DataParser.ts:612]: I couldn't see this causing any issues (but happy to be told I'm wrong 😆 ), needed for RxNav and NZULM codes to show up for the COVID vaccine products as they had a uc7 but still needed properties assigned at the uc2 level

Comment (mark-prins) [reply unified-codes/apps/data-loader/src/app/v2/DataParser.ts:612]: IIRC there was an issue because UC7 wasn't implemented in our code.
Importing the UC2 value for items that had UC7 resulted in something unwanted - I would think parents with no children? Should be ok now though

**Review by mark-prins — APPROVED** [review]
LGTM

**Comment by katherine-sussol** [comment]
I nearly forgot about this PR 🤣  thanks for the review, will merge! The COVID vaccine codes have been live for a while as I think someone needed them somewhere
