### PR TITLE
#110 fix issues with nx web project

### LINKED ISSUE #110: Fix nx web project paths
The current web builds; but no longer serves any content. Paths in `index.html` are incorrect and there's a lot of warnings displayed.

## Expected Behaviour
Running `nx serve web` should show the index page with explorer on `http://localhost:4200`

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #110 

## Description
Resolves warnings and errors - gets the react app running again when using `nx serve web1`

### Documentation:

Tick below if one of the following applies:

1. Documentation has been added to cover changes introduced by this PR.
2. This PR requires no changes to documentation.

- [x] Documentation OK.

### Tests:

Tick below if one of the following applies:

1. Tests have been added to cover changes introduced by this PR.
2. This PR requires no new tests.

- [x] Tests OK.

### CODE REVIEW

File: nx-workspace/apps/web/src/components/atoms/core/AppBar.tsx [hunk 1]
```diff
@@ -1 +1,4 @@
-export { AppBar, AppBarProps } from "@material-ui/core";
+import { AppBarProps as t_AppBarProps } from "@material-ui/core";
+
+export { AppBar } from "@material-ui/core";
+export type AppBarProps = t_AppBarProps;
```
Comment (wlthomson) [inline nx-workspace/apps/web/src/components/atoms/core/AppBar.tsx:4]: Assuming this is a warning about exporting a value with a type? Does it fix it to export them separately, e.g.:

```suggestion
import { AppBarProps as t_AppBarProps } from "@material-ui/core";

export { AppBar } from "@material-ui/core";
export type AppBarProps = t_AppBarProps;
```

```suggestion
export { AppBar } from "@material-ui/core";
export { AppBarProps } from "@material-ui/core";
```

Or, alternatively:

```suggestion
export { AppBar } from "@material-ui/core";
import { AppBarProps as MAppBarProps } from "@material-ui/core";
export type AppBarProps = MAppBarProps;
```

File: nx-workspace/apps/web/src/components/atoms/core/index.tsx [hunk 2]
```diff
@@ -1,34 +1,28 @@
-export { Alert, AlertProps, Severity } from "./Alert";
-export { AppBar, AppBarProps } from "./AppBar";
-export { Box, BoxProps } from "./Box";
-export { Button, ButtonProps } from "./Button";
+export * from "./Alert";
+export * from "./AppBar";
+export * from "./Box";
+export * from "./Button";
 export { ClearIcon } from "./ClearIcon";
```
Comment (wlthomson) [inline nx-workspace/apps/web/src/components/atoms/core/index.tsx:5]: Hmm, I thought being explicit here might be better, but if we go with `*`, maybe use it for every export?
