### PR TITLE
#100 handle apollo errors in ui

### LINKED ISSUE #100: Handle apollo errors in web ui
If the apollo server isn't responding r the URL is misconfigured then the entitybrowser component silently fails.
I'd prefer it to tell me that something is wrong.

## Expected Behaviour
If the server isn't working, tell me.
Nice to have a loading indicator if possible.

## Current Behaviour
Nothing happens.

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #100 

## Description
Adds snackbar and alert components, including adding to storybook.
Displays an error alert if the entityBrowser ( in storybook ) fails to fetch.

## Next Steps
- Add a global snackbar to the app
- Wire this up using redux, when available
- Create an EntityBrowser which fetches and handles errors, so that we don't have to recreate these storybook changes in the main app

### Documentation:

Tick below if one of the following applies:

1. Documentation has been added to cover changes introduced by this PR.
2. This PR requires no changes to documentation.

- [x] Documentation OK.

### Tests:

Tick below if one of the following applies:

1. Tests have been added to cover changes introduced by this PR.
2. This PR requires no new tests.

- [x] Tests OK.

### CODE REVIEW

File: nx-workspace/apps/web/src/components/atoms/core/Alert.tsx [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import * as React from "react";
+import MAlert, {
+  AlertProps as MAlertProps,
+  Color,
+} from "@material-ui/lab/Alert";
+
+export interface AlertProps extends MAlertProps {
+  Color?: Color;
```
Comment (wlthomson) [inline nx-workspace/apps/web/src/components/atoms/core/Alert.tsx:8]: Just double checking that `Alert` doesn't have style props for setting color?

File: nx-workspace/apps/web/src/components/atoms/core/Snackbar.tsx [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+import {
+  Snackbar as MSnackbar,
+  SnackbarProps as MSnackbarProps,
+} from "@material-ui/core";
+
+export interface SnackbarProps extends MSnackbarProps {}
+
+export type Snackbar = React.FunctionComponent<SnackbarProps>;
+
+export const Snackbar = (props: SnackbarProps) => <MSnackbar {...props} />;
```
Comment (wlthomson) [inline nx-workspace/apps/web/src/components/atoms/core/Snackbar.tsx:11]: Sorry, bad precedent set by my old atoms!

Can replace this with:

```
export { Snackbar, SnackbarProps } from "@material-ui/core";
```

File: nx-workspace/apps/web/stories/Alert.stories.tsx [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+};
+export const warningAlert = () => {
+  return <Alert severity="warning">This is a warning message!</Alert>;
+};
+export const informationAlert = () => {
+  return <Alert severity="info">This is an information message</Alert>;
+};
+export const successAlert = () => {
+  return <Alert severity="success">This is a success message!</Alert>;
+};
```
Comment (wlthomson) [inline nx-workspace/apps/web/stories/Alert.stories.tsx:17]: thumbsup2

File: nx-workspace/apps/web/stories/EntityBrowser.stories.tsx [hunk 4]
```diff
@@ -23,6 +23,12 @@ export const withMockData = () => {
 };
 
 export const withApolloData = () => {
+  type UserAlert = {
+    severity: AlertProps["Color"];
+    show: boolean;
+    text: string;
+  };
+  const defaultAlert: UserAlert = { show: false, text: "", severity: "info" };
```
Comment (wlthomson) [inline nx-workspace/apps/web/stories/EntityBrowser.stories.tsx:31]: thumbsup

File: nx-workspace/apps/web/stories/Snackbar.stories.tsx [hunk 5]
```diff
@@ -0,0 +1,118 @@
...
+        horizontal: "center",
+      }}
+      open={open}
+      autoHideDuration={5000}
+      onClose={() => setOpen(false)}
+      message="This message will self-close in 5s"
+      action={
+        <React.Fragment>
+          <Button color="secondary" size="small" onClick={() => setOpen(false)}>
+            CLOSE
```
Comment (wlthomson) [inline nx-workspace/apps/web/stories/Snackbar.stories.tsx:91]: I think casing is handled by component + styling (IIRC, button labels will be capital case by default).

File: nx-workspace/apps/web/stories/Snackbar.stories.tsx [hunk 6]
```diff
@@ -0,0 +1,118 @@
...
+export const withAlert = () => {
+  const [open, setOpen] = React.useState(true);
+  return (
+    <Snackbar
+      open={open}
+      autoHideDuration={5000}
+      onClose={() => setOpen(false)}
+    >
+      <Alert severity="success" onClose={() => setOpen(false)}>
+        Succesfully displayed snackbar!
```
Comment (wlthomson) [inline nx-workspace/apps/web/stories/Snackbar.stories.tsx:114]: Nit: typo.

File: nx-workspace/apps/web/src/components/atoms/core/Alert.tsx (hunk 1 above)
Comment (mark-prins) [reply nx-workspace/apps/web/src/components/atoms/core/Alert.tsx:8]: it has a root level prop for `Color` which is used if provided - otherwise it is set by `Severity`
Agree, this ambiguity is not good though - I've now lifted the type out and exported it directly.

File: nx-workspace/apps/web/src/components/atoms/core/Snackbar.tsx (hunk 2 above)
Comment (mark-prins) [reply nx-workspace/apps/web/src/components/atoms/core/Snackbar.tsx]: Yes! 30f9e704c

File: nx-workspace/apps/web/stories/Snackbar.stories.tsx (hunk 5 above)
Comment (mark-prins) [reply nx-workspace/apps/web/stories/Snackbar.stories.tsx:91]: YES. THAT'S TRUE! THANKS! OOPS. COPIED FROM MATERIAL-UI SAMPLE!

File: nx-workspace/apps/web/stories/Snackbar.stories.tsx (hunk 6 above)
Comment (mark-prins) [reply nx-workspace/apps/web/stories/Snackbar.stories.tsx:114]: unsuccessfully spelled word!

**Comment by mark-prins** [comment]
Thanks @wlthomson! - addressed the review comments

**Comment by wlthomson** [comment]
> Looks good to me (aside from the obvious misspelling of 'colour' 😼 )

uk
