### PR TITLE
#363 Fix CI Build

### LINKED ISSUE #363: CI build failing consistently
## Expected Behaviour

- Passing CI builds and less email spam every commit

## Current Behaviour

- Failing CI builds and GitHub email spam

## Possible Solution

- Fix the build
- Alternatively, unsubscribe from email alerts. But then may as well delete CI 🤷 

## Steps to Reproduce (bugs only, delete if not applicable)

1. Commit some code to a UC branch
2. See email alerts and panic

image

### PR DESCRIPTION
**Pull request by katherine-sussol**
Fixes #363 

## Description

- Pluralise `entity` and `property` folders to distinguish them from the entity and property files
- Update references
- Checked last CI build - was 🟢 
- Please no 🐱 🔫  , happy to change the names if there's a better suggestion!

### Documentation:

Tick below if one of the following applies:

1. Documentation has been added to cover changes introduced by this PR.
2. This PR requires no changes to documentation.

- [x] Documentation OK.

### Tests:

Tick below if one of the following applies:

1. Tests have been added to cover changes introduced by this PR.
2. This PR requires no new tests.

- [x] Tests OK.

### CODE REVIEW

File: unified-codes/libs/data/src/lib/v2/entities/FormEntity.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import { EEntityType, IEntity, Entity } from './Entity';
 import { IFormQualifierEntity, FormQualifierEntity } from './FormQualifierEntity';
 import { IUnitEntity, UnitEntity } from './UnitEntity';
-import { IProperty, Property } from '../Property';
+import { IProperty, Property } from '../properties';
```
Comment (wlthomson) [inline unified-codes/libs/data/src/lib/v2/entities/FormEntity.ts:4]: Nit: since these imports both coming from `'../properties/Property'`, may as well directly import from there? E.g.

```
import { IProperty, Property } from '../properties/Property';
```

**Review by wlthomson — APPROVED** [review]
LGTM!

giphy

File: unified-codes/libs/data/src/lib/v2/entities/FormEntity.ts (hunk 1 above)
Comment (katherine-sussol) [reply unified-codes/libs/data/src/lib/v2/entities/FormEntity.ts]: Hmm yeah, why not - done with b0cb9ddd2.
Let's see how the next CI run goes 🤞
