### PR TITLE
#368 fix msupply query duplicate descriptors

### LINKED ISSUE #368: Duplicate descriptors in mSupply query results
mSupply query handler recursively constructs entity names at query time. This step is now done at the data preprocessing stage (see #367) and needs to be removed to avoid duplicate descriptors.

## Expected Behaviour

mSupply code lookup returns items with full descriptors (without duplication).

## Current Behaviour

mSupply code lookup returns items with duplicated descriptors.

## Possible Solution

Remove recursive name traversal from mSupply query handling logic.

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #368.

Branched off #367. 

## Description

Migrates mSupply query to updated dgraph data format.

Removes a lot of post-processing from the previous query handler, so code is a bit less messy and query probably a fair bit quicker for bigger data sets.

### Documentation:

Tick below if one of the following applies:

1. Documentation has been added to cover changes introduced by this PR.
2. This PR requires no changes to documentation.

- [ ] Documentation OK.

### Tests:

Tick below if one of the following applies:

1. Tests have been added to cover changes introduced by this PR.
2. This PR requires no new tests.

- [ ] Tests OK.

### CODE REVIEW

File: unified-codes/apps/data-loader/src/app/v2/DataParser.ts [hunk 1]
```diff
@@ -146,6 +146,8 @@ export class DataParser {
       [UC_ENTITY.CONSUMABLE.code]: UC_ENTITY.CONSUMABLE,
     };
 
+    UC_ENTITY.ROOT.children = [UC_ENTITY.DRUG, UC_ENTITY.CONSUMABLE];
```
Comment (katherine-sussol) [inline unified-codes/apps/data-loader/src/app/v2/DataParser.ts:149]: 👍

File: unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts [hunk 2]
```diff
@@ -133,16 +135,15 @@ export class DgraphDataSource extends RESTDataSource {
     const categoryString = this.getEntityCategoryString(categories);
     const orderString = this.getEntitiesOrderString(orderField, orderDesc);
     const filterString = this.getEntitiesFilterString(description, match);
-    const isMsupply = types.includes(EEntityType.UNIT_OF_USE);
 
+    // Required for backwards compatiblility with broken mSupply query. 
+    // Query incorrectly specifies medical_product as a type instead of category.
+    const isMsupply = types.includes(EEntityCategory.MEDICINAL_PRODUCT);
```
Comment (katherine-sussol) [inline unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts:141]: Ah, I see what you did here 👀 , clever.

File: unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts [hunk 3]
```diff
@@ -133,16 +135,15 @@ export class DgraphDataSource extends RESTDataSource {
...
+
+    // TODO: migrate query to mSupply and remove hardcoded query mapping.
```
Comment (katherine-sussol) [inline unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts:143]: Looking forward to it heh heh. When we update would be good to document which version(s) have the old one so we can guesstimate when to remove it (if ever? 😿 )

File: unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts [hunk 4]
```diff
@@ -330,110 +295,6 @@ export class DgraphDataSource extends RESTDataSource {
       return { ...DgraphDataSource.mapEntity(entity), interactions };
     });
 
-
-    if (isMsupply) {
```
Comment (katherine-sussol) [inline unified-codes/apps/data-service/src/app/v1/types/DgraphDataSource.ts:334]: 🧹 👍

**Review by katherine-sussol — APPROVED** [review]
LGTM!
Well Done Minions
